module SQLProperties

  ACTIVE_FLG_ON = "1";

  # 稼働日取得
  SQL_DT_DMY_OPERATING_DAY_SELECT = "SELECT DT_DMY_OPERATING_DAY FROM sys_operating_day WHERE CD_SYSEM = 'NNK' AND ACTIVE_FLG = '1'"
  # 稼働日更新
  SQL_DT_DMY_OPERATING_DAY_UPDATE = "UPDATE sys_operating_day SET DT_DMY_OPERATING_DAY = date_add(DT_DMY_OPERATING_DAY, interval 1 day) WHERE CD_SYSEM = 'NNK' AND ACTIVE_FLG = '1'";


  SQL_LOOKUP_SELECT = "SELECT ELEMENT_TEXT FROM SYS_LOOKUP WHERE CD_LOOKUP_TYPE = ? AND CD_LOOKUP_NAME = ? AND ACTIVE_FLG = ?"
  BRAND_CODE_SELECT_SQL = "SELECT COUNT(CD_BRAND) AS CNT_BRAND FROM NNK_CORPORATE_INFO WHERE CD_BRAND = ? AND ACTIVE_FLG = ?"
  CORPORATE_INFO_INSERT = "INSERT INTO NNK_CORPORATE_INFO (CD_BRAND, CREATION_DATE,ACTIVE_FLG, NM_CORPORATE, FL_DEALINGS_TARGET) VALUES (?,NOW(), ?, ?, ?)";
  CORPORATE_NM_CORPORATE_UPDATE = "UPDATE NNK_CORPORATE_INFO SET LAST_UPDATE_DATE = NOW(), NM_CORPORATE = ? WHERE CD_BRAND = ?  AND ACTIVE_FLG = ?";
  CORPORATE_NM_BPS_UPDATE = "UPDATE NNK_CORPORATE_INFO SET LAST_UPDATE_DATE = NOW(), AM_BPS_FIRST_TERM = ?, AM_BPS_TWO_TERMS = ?, AM_BPS_THREE_TERMS = ?, AM_PROFIT_CURRENT_FIRST_TERM = ?, AM_PROFIT_CURRENT_TWO_TERMS = ?, AM_PROFIT_CURRENT_THREE_TERMS = ? WHERE CD_BRAND = ? AND ACTIVE_FLG = ?";
  SQL_STOCK_PRICES_SERIES_DAILY_INSERT = "INSERT INTO NNK_STOCK_PRICES_SERIES_DAILY (CD_BRAND, CD_BRAND_SQE, CREATION_DATE, ACTIVE_FLG, DT_THE_DAY, AM_OPENING_PRICE, AM_HIGH_PRICE, AM_LOW_PRICE, AM_CLOSING_PRICE, AM_TRADING_VOLUME) VALUES (?, ?, NOW(), ?, ?, ?, ?, ?, ?, ?)";
  SQL_AM_STOCK_PRICE_UPDATE = "UPDATE NNK_CORPORATE_INFO SET LAST_UPDATE_DATE = NOW(), AM_STOCK_PRICE = ? WHERE CD_BRAND = ? AND ACTIVE_FLG = ?";


end